name: SE333_CI
on:
  push:
    branches:
      - main

jobs:
  SE333_CI_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setupJava
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Install Linter
        ##TODO
        run: mvn -B validate
      - name: Run Checkstyle
        ##TODO
        run: mvn checkstyle:checkstyle
      - name: Upload Checkstyle Result
        ##TODO
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/checkstyle-result.xml
      - name: Run Maven Test
        ##TODO
        run: mvn -B test
      - name: Jacoco Report
        ##TODO
        run: mvn -B jacoco:report